#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
cd $ROOT
make -C evawiz release
EVAWIZ_ROOT=$ROOT
if ! [ -f $EVAWIZ_ROOT/evawiz.source.local ]; then
    mv $EVAWIZ_ROOT/evawiz.source.local.ori $EVAWIZ_ROOT/evawiz.source.local
fi
sed -i "s#ROOT=\/opt\/evawiz#ROOT=$EVAWIZ_ROOT#"  $EVAWIZ_ROOT/evawiz.source
if ! [ -d $idr ];then
  dir=/opt/evawiz
fi
re=`cat ~/.bashrc |grep "source $dir/evawiz.source"`
if [ "x$re" == "x" ]; then
  echo "source $dir/evawiz.source">>~/.bashrc
  source $dir/evawiz.source
fi

